// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthControllerLoginData, AuthControllerLoginErrors, AuthControllerLoginResponses, AuthControllerRegisterData, AuthControllerRegisterErrors, AuthControllerRegisterResponses, BookingsControllerCreateData, BookingsControllerCreateResponses, BookingsControllerFindAllData, BookingsControllerFindAllResponses, BookingsControllerFindOneData, BookingsControllerFindOneResponses, BookingsControllerUpdateStatusData, BookingsControllerUpdateStatusResponses, DashboardControllerGetStatsData, DashboardControllerGetStatsResponses, HotelsControllerCreateData, HotelsControllerCreateResponses, HotelsControllerFindAllData, HotelsControllerFindAllResponses, HotelsControllerFindOneData, HotelsControllerFindOneResponses, HotelsControllerRemoveData, HotelsControllerRemoveResponses, HotelsControllerUpdateData, HotelsControllerUpdateResponses, RoomsControllerCreateData, RoomsControllerCreateResponses, RoomsControllerFindAllData, RoomsControllerFindAllResponses, RoomsControllerFindOneData, RoomsControllerFindOneResponses, RoomsControllerRemoveData, RoomsControllerRemoveResponses, RoomsControllerUpdateData, RoomsControllerUpdateResponses, UsersControllerFindAllData, UsersControllerFindAllResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Register a new user
 */
export const authControllerRegister = <ThrowOnError extends boolean = false>(options: Options<AuthControllerRegisterData, ThrowOnError>) => (options.client ?? client).post<AuthControllerRegisterResponses, AuthControllerRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Login user
 */
export const authControllerLogin = <ThrowOnError extends boolean = false>(options: Options<AuthControllerLoginData, ThrowOnError>) => (options.client ?? client).post<AuthControllerLoginResponses, AuthControllerLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all users (Admin only)
 */
export const usersControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<UsersControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<UsersControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users',
    ...options
});

/**
 * Get all hotels with search and pagination
 */
export const hotelsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<HotelsControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<HotelsControllerFindAllResponses, unknown, ThrowOnError>({ url: '/hotels', ...options });

/**
 * Create a new hotel
 */
export const hotelsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<HotelsControllerCreateData, ThrowOnError>) => (options.client ?? client).post<HotelsControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/hotels',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a hotel
 */
export const hotelsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<HotelsControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<HotelsControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/hotels/{id}',
    ...options
});

/**
 * Get hotel by ID
 */
export const hotelsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<HotelsControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<HotelsControllerFindOneResponses, unknown, ThrowOnError>({ url: '/hotels/{id}', ...options });

/**
 * Update a hotel
 */
export const hotelsControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<HotelsControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<HotelsControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/hotels/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all rooms
 */
export const roomsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<RoomsControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<RoomsControllerFindAllResponses, unknown, ThrowOnError>({ url: '/rooms', ...options });

/**
 * Create a new room
 */
export const roomsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<RoomsControllerCreateData, ThrowOnError>) => (options.client ?? client).post<RoomsControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete a room
 */
export const roomsControllerRemove = <ThrowOnError extends boolean = false>(options: Options<RoomsControllerRemoveData, ThrowOnError>) => (options.client ?? client).delete<RoomsControllerRemoveResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms/{id}',
    ...options
});

/**
 * Get room by ID
 */
export const roomsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<RoomsControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<RoomsControllerFindOneResponses, unknown, ThrowOnError>({ url: '/rooms/{id}', ...options });

/**
 * Update a room
 */
export const roomsControllerUpdate = <ThrowOnError extends boolean = false>(options: Options<RoomsControllerUpdateData, ThrowOnError>) => (options.client ?? client).patch<RoomsControllerUpdateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/rooms/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get all bookings
 */
export const bookingsControllerFindAll = <ThrowOnError extends boolean = false>(options?: Options<BookingsControllerFindAllData, ThrowOnError>) => (options?.client ?? client).get<BookingsControllerFindAllResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bookings',
    ...options
});

/**
 * Create a new booking
 */
export const bookingsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<BookingsControllerCreateData, ThrowOnError>) => (options.client ?? client).post<BookingsControllerCreateResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bookings',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get booking by ID
 */
export const bookingsControllerFindOne = <ThrowOnError extends boolean = false>(options: Options<BookingsControllerFindOneData, ThrowOnError>) => (options.client ?? client).get<BookingsControllerFindOneResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bookings/{id}',
    ...options
});

/**
 * Update booking status
 */
export const bookingsControllerUpdateStatus = <ThrowOnError extends boolean = false>(options: Options<BookingsControllerUpdateStatusData, ThrowOnError>) => (options.client ?? client).patch<BookingsControllerUpdateStatusResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/bookings/{id}/status',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get dashboard statistics
 */
export const dashboardControllerGetStats = <ThrowOnError extends boolean = false>(options?: Options<DashboardControllerGetStatsData, ThrowOnError>) => (options?.client ?? client).get<DashboardControllerGetStatsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/dashboard/stats',
    ...options
});
