// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: string;
};

export type RegisterDto = {
    name: string;
    email: string;
    password: string;
    role: 'ADMIN' | 'HOTEL_MANAGER';
};

export type LoginDto = {
    email: string;
    password: string;
};

export type CreateHotelDto = {
    name: string;
    city: string;
    address: string;
    stars: number;
    status?: 'ACTIVE' | 'INACTIVE';
};

export type UpdateHotelDto = {
    name?: string;
    city?: string;
    address?: string;
    stars?: number;
    status?: 'ACTIVE' | 'INACTIVE';
};

export type CreateRoomDto = {
    hotelId: string;
    roomType: string;
    capacity: number;
    pricePerNight: number;
    availableRoomsCount: number;
};

export type UpdateRoomDto = {
    hotelId?: string;
    roomType?: string;
    capacity?: number;
    pricePerNight?: number;
    availableRoomsCount?: number;
};

export type CreateBookingDto = {
    hotelId: string;
    roomId: string;
    checkIn: string;
    checkOut: string;
    guestCount: number;
};

export type UpdateBookingStatusDto = {
    status: 'PENDING' | 'CONFIRMED' | 'CANCELLED';
};

export type AuthControllerRegisterData = {
    body: RegisterDto;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type AuthControllerRegisterErrors = {
    /**
     * Email already exists
     */
    409: unknown;
};

export type AuthControllerRegisterResponses = {
    /**
     * User registered successfully
     */
    201: unknown;
};

export type AuthControllerLoginData = {
    body: LoginDto;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthControllerLoginErrors = {
    /**
     * Invalid credentials
     */
    401: unknown;
};

export type AuthControllerLoginResponses = {
    /**
     * Login successful
     */
    200: any;
};

export type UsersControllerFindAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users';
};

export type UsersControllerFindAllResponses = {
    200: unknown;
};

export type HotelsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        search?: string;
        page?: number;
        limit?: number;
    };
    url: '/hotels';
};

export type HotelsControllerFindAllResponses = {
    200: unknown;
};

export type HotelsControllerCreateData = {
    body: CreateHotelDto;
    path?: never;
    query?: never;
    url: '/hotels';
};

export type HotelsControllerCreateResponses = {
    201: unknown;
};

export type HotelsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/hotels/{id}';
};

export type HotelsControllerRemoveResponses = {
    200: unknown;
};

export type HotelsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/hotels/{id}';
};

export type HotelsControllerFindOneResponses = {
    200: unknown;
};

export type HotelsControllerUpdateData = {
    body: UpdateHotelDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/hotels/{id}';
};

export type HotelsControllerUpdateResponses = {
    200: unknown;
};

export type RoomsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        hotelId?: string;
    };
    url: '/rooms';
};

export type RoomsControllerFindAllResponses = {
    200: unknown;
};

export type RoomsControllerCreateData = {
    body: CreateRoomDto;
    path?: never;
    query?: never;
    url: '/rooms';
};

export type RoomsControllerCreateResponses = {
    201: unknown;
};

export type RoomsControllerRemoveData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type RoomsControllerRemoveResponses = {
    200: unknown;
};

export type RoomsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type RoomsControllerFindOneResponses = {
    200: unknown;
};

export type RoomsControllerUpdateData = {
    body: UpdateRoomDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/rooms/{id}';
};

export type RoomsControllerUpdateResponses = {
    200: unknown;
};

export type BookingsControllerFindAllData = {
    body?: never;
    path?: never;
    query?: {
        status?: string;
    };
    url: '/bookings';
};

export type BookingsControllerFindAllResponses = {
    200: unknown;
};

export type BookingsControllerCreateData = {
    body: CreateBookingDto;
    path?: never;
    query?: never;
    url: '/bookings';
};

export type BookingsControllerCreateResponses = {
    201: unknown;
};

export type BookingsControllerFindOneData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/bookings/{id}';
};

export type BookingsControllerFindOneResponses = {
    200: unknown;
};

export type BookingsControllerUpdateStatusData = {
    body: UpdateBookingStatusDto;
    path: {
        id: string;
    };
    query?: never;
    url: '/bookings/{id}/status';
};

export type BookingsControllerUpdateStatusResponses = {
    200: unknown;
};

export type DashboardControllerGetStatsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/dashboard/stats';
};

export type DashboardControllerGetStatsResponses = {
    200: unknown;
};
